### ISSUE TITLE
论文细节的请教

### ISSUE THREAD

**Issue by 3030curry30** [Zce1112zslx/IKE#1]
您好，很有幸拜读了这篇文章，有几个问题想请教一下作者：1. 该方法是通过构造Prompt来完成一次性的knowledge editing, 这是否和 Retrieval-Augmented 更相关一些？2. 既然是一次性的修正，为什么需要引入无关的fact，没有梯度修正，应该不会影响别的事实正确性？

**Comment by wutaiqiang** [comment]
和 memory based model edit 还是很类似的，作者在论文最后也讲了一下

ICL 就是要引入一些 demonstrate 来给 LLM 打个样
